project:
  type: website

website:
  title: "PAULO BARROS"
  favicon: favicon-32x32.png
  twitter-card:
    creator: "@pbarrosjr"
    image: "https://www.paulobarros.com.br/Avatar2023.png"
  site-url: "https://paulobarros.com.br"
  navbar:
      logo: LogoPB_wb.png
      #title: true
      right:
      - text: BIO
        file: about.qmd
      - text: POSTS
        menu:
          - text: Portuguese (BR)
            file: posts/index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: envelope
        href: mailto:pbarrosbio@gmail.com
format:
  html:
    theme: 
      - litera
      - pb-quarto.scss
    css: styles.css
    highlight-style: dracula
    code-line-numbers: true
    toc: true

editor: source

